name: 'Simple github deployment'
description: 'Simple github deployment'
author: 'Jakub'
inputs:
  ref:
    description: The ref to deploy. This can be a branch, tag, or SHA.
    required: true
  target:
    description: >
      Name for the target deployment environment (production, staging)
    required: true
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  description:
    description: Short description of the deployment.
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
